Repository iver-wharf/wharf-cmd, pull requests merged in 2022-03, with the labels that each got.

#59 Added swaggo docs to provisionerapi
  .github/workflows/go-test.yml
  CHANGELOG.md
  Makefile
  go.mod
  go.sum
  pkg/provisionerapi/.gitignore
  pkg/provisionerapi/provisionerapi.go
  pkg/provisionerapi/worker.go
Labels: enhancement, c/provisioner

#58 Added env var sub support
  CHANGELOG.md
  cmd/run.go
  pkg/varsub/source.go
  pkg/varsub/varsub.go
  pkg/varsub/varsub_test.go
  pkg/wharfyml/definition.go
  pkg/wharfyml/parse.go
  pkg/wharfyml/parse_test.go
  pkg/wharfyml/varsub.go
  pkg/wharfyml/visitor.go
Labels: enhancement, c/worker

#64 CLI docs & completions
  CHANGELOG.md
  cmd/provisioner.go
  cmd/provisioner_create.go
  cmd/provisioner_delete.go
  cmd/provisioner_list.go
  cmd/provisioner_serve.go
  cmd/run.go
  go.mod
  go.sum
Labels: documentation, enhancement, c/provisioner, c/worker

#62 Added watchdog serve
  CHANGELOG.md
  cmd/watchdog.go
  cmd/watchdog_serve.go
  go.mod
  go.sum
  pkg/provisioner/worker.go
  pkg/provisionerapi/provisionerapi.go
  pkg/provisionerclient/provisionerclient.go
  pkg/provisionerclient/provisionerclient_test.go
  pkg/watchdog/watchdog.go
  pkg/watchdog/watchdog_test.go
Labels: enhancement, c/watchdog

#63 Added kubectl flags
  CHANGELOG.md
  cmd/provisioner.go
  cmd/provisioner_create.go
  cmd/provisioner_delete.go
  cmd/provisioner_list.go
  cmd/provisioner_serve.go
  cmd/root.go
  cmd/run.go
  go.mod
  pkg/provisionerapi/provisionerapi.go
  pkg/provisionerapi/worker.go
Labels: enhancement, c/provisioner, c/worker

#66 Step runner factory
  CHANGELOG.md
  cmd/run.go
  pkg/worker/builder.go
  pkg/worker/builder_test.go
  pkg/worker/k8srunner.go
  pkg/worker/stagerunner.go
  pkg/worker/stagerunner_test.go
  pkg/worker/worker.go
Labels: enhancement, c/worker

#67 Added pkg/gitstat
  CHANGELOG.md
  pkg/gitstat/gitstat.go
Labels: enhancement

#51 Issue 14 - Worker gRPC & HTTP
  CHANGELOG.md
  Makefile
  api/workerapi/v1/worker.pb.go
  api/workerapi/v1/worker.proto
  api/workerapi/v1/worker_grpc.pb.go
  go.mod
  go.sum
  pkg/resultstore/artifact.go
  pkg/resultstore/artifact_test.go
  pkg/resultstore/resultstore.go
  pkg/wharfyml/definition.go
  pkg/worker/artifact.go
  pkg/workerapi/workerclient/grpcclient.go
  pkg/workerapi/workerclient/grpcclient_test.go
  pkg/workerapi/workerclient/restclient.go
  pkg/workerapi/workerclient/restclient_test.go
  pkg/workerapi/workerclient/workerclient.go
  pkg/workerapi/workerclient/workerclient_test.go
  pkg/workerapi/workerserver/artifact.go
  pkg/workerapi/workerserver/grpcserver.go
  pkg/workerapi/workerserver/restserver.go
  pkg/workerapi/workerserver/server.go
Labels: c/worker

#69 Added getting Git remotes to pkg/gitstat
  CHANGELOG.md
  pkg/gitstat/gitstat.go
  pkg/gitstat/gitstat_test.go
Labels: enhancement

#70 Fixed circular imports for worker
  CHANGELOG.md
  cmd/run.go
  pkg/provisioner/worker.go
  pkg/provisioner/worker_test.go
  pkg/resultstore/artifact.go
  pkg/resultstore/artifact_test.go
  pkg/resultstore/resultstore.go
  pkg/resultstore/status.go
  pkg/resultstore/status_test.go
  pkg/watchdog/watchdog.go
  pkg/worker/builder.go
  pkg/worker/builder_test.go
  pkg/worker/k8srunner.go
  pkg/worker/stagerunner.go
  pkg/worker/stagerunner_test.go
  pkg/worker/status_test.go
  pkg/worker/worker.go
  pkg/worker/workermodel/artifact.go
  pkg/worker/workermodel/status.go
  pkg/workerapi/workerserver/grpcserver.go
Labels: enhancement

#71 Added storing of build results using resultstore
  CHANGELOG.md
  cmd/run.go
  pkg/resultstore/fs.go
  pkg/resultstore/resultstore.go
  pkg/worker/builder.go
  pkg/worker/builder_test.go
  pkg/worker/k8srunner.go
  pkg/worker/stagerunner.go
  pkg/worker/stagerunner_test.go
  pkg/worker/worker.go
Labels: enhancement

#74 Updated to Go v1.18
  .github/workflows/go-format.yml
  .github/workflows/go-test.yml
  CHANGELOG.md
  Dockerfile
  README.md
  go.mod
  go.sum
  pkg/resultstore/keyedmutex.go
  pkg/varsub/source.go
  pkg/varsub/varsub.go
  pkg/varsub/varsub_test.go
  pkg/wharfyml/environment.go
  pkg/wharfyml/environment_test.go
  pkg/wharfyml/varsub.go
Labels: chore

#75 Added go-typ
  CHANGELOG.md
  go.mod
  go.sum
  internal/slices/slices.go
  internal/slices/slices_test.go
  pkg/resultstore/artifact.go
  pkg/resultstore/artifact_test.go
  pkg/resultstore/keyedmutex.go
  pkg/resultstore/logline.go
  pkg/resultstore/logline_test.go
  pkg/resultstore/resultstore.go
  pkg/resultstore/status.go
  pkg/resultstore/status_test.go
  pkg/wharfyml/builtins.go
  pkg/workerapi/workerserver/grpcserver.go
Labels: chore

#76 Added canary build and `--version`
  .wharf-ci.yml
  CHANGELOG.md
  Dockerfile
  Makefile
  assets/version.yaml
  cmd/root.go
  main.go
  scripts/update-version.sh
Labels: enhancement

#78 Added safeexec.LookPath in pkg/gitstat
  CHANGELOG.md
  go.mod
  go.sum
  pkg/gitstat/gitstat.go
Labels: chore
