Repository iver-wharf/wharf-cmd, pull requests merged in 2022-05, with the labels that each got.

#117 Added query params for the provisioner
  .dockerignore
  CHANGELOG.md
  Dockerfile
  Makefile
  cmd/wharf/provisioner.go
  cmd/wharf/provisioner_create.go
  cmd/wharf/provisioner_delete.go
  cmd/wharf/provisioner_list.go
  cmd/wharf/provisioner_serve.go
  cmd/wharf/run.go
  cmd/wharf/utils.go
  cmd/wharf/vars.go
  pkg/provisioner/k8sprovisioner.go
  pkg/provisioner/provisioner.go
  pkg/provisionerapi/.gitignore
  pkg/provisionerapi/provisionerapi.go
  pkg/provisionerapi/worker.go
  pkg/workerapi/workerserver/.gitignore
  pkg/workerapi/workerserver/artifact.go
  pkg/workerapi/workerserver/restserver.go
Labels: enhancement, c/provisioner

#120 Support for Git credentials from k8s secret
  CHANGELOG.md
  docs/provisioner-git-ssh-secret.md
  pkg/provisioner/k8sprovisioner.go
Labels: enhancement, c/provisioner

#126 Aggregator updates build status
  CHANGELOG.md
  api/workerapi/v1/worker.pb.go
  api/workerapi/v1/worker.proto
  pkg/aggregator/aggregator.go
  pkg/aggregator/k8saggregator.go
  pkg/workerapi/workerclient/workerclient.go
  pkg/workerapi/workerserver/grpcserver.go
Labels: enhancement, c/aggregator

#127 Update go-typ to v4
  CHANGELOG.md
  cmd/wharf/run.go
  cmd/wharf/utils.go
  cmd/wharf/vars_list.go
  cmd/wharf/vars_substitute.go
  go.mod
  go.sum
  internal/ignorer/ignorer.go
  pkg/aggregator/k8saggregator.go
  pkg/provisioner/k8sprovisioner.go
  pkg/resultstore/logline.go
  pkg/resultstore/resultstore.go
  pkg/resultstore/syncset.go
  pkg/tarstore/tarstore.go
  pkg/varsub/varsub.go
  pkg/worker/k8spodtemplating.go
  pkg/workerapi/workerserver/server.go
Labels: chore

#128 Updated Makefile
  Makefile
Labels: chore

#121 Added non-git local vars to provisioned workers
  CHANGELOG.md
  cmd/wharf/provisioner_create.go
  cmd/wharf/utils.go
Labels: enhancement, c/provisioner

#129 Fix minor issues
  CHANGELOG.md
  cmd/wharf/aggregator.go
  cmd/wharf/aggregator_serve.go
  cmd/wharf/provisioner_create.go
  cmd/wharf/provisioner_list.go
  pkg/aggregator/k8saggregator.go
  pkg/provisioner/worker.go
  pkg/provisioner/worker_test.go
  pkg/provisionerapi/worker.go
  pkg/watchdog/watchdog.go
  pkg/watchdog/watchdog_test.go
Labels: bug, enhancement, c/provisioner, c/watchdog

#130 Fixed `make docker-run`
  Makefile
Labels: chore

#131 Fixed `wharf vars -i/-e` & `wharf aggregator --instance`
  CHANGELOG.md
  cmd/wharf/aggregator.go
  cmd/wharf/provisioner_create.go
  cmd/wharf/run.go
  cmd/wharf/utils.go
  cmd/wharf/vars.go
  cmd/wharf/vars_list.go
Labels: bug

#132 Fix race conditions
  pkg/worker/stagerunner.go
Labels: bug

#134 Added user config dir support
  CHANGELOG.md
  pkg/config/config.go
Labels: enhancement

#136 staticcheck fixes
  CHANGELOG.md
  cmd/wharf/root.go
  cmd/wharf/run.go
Labels: chore

#137 watchdog: Dont filter workers
  CHANGELOG.md
  pkg/watchdog/watchdog.go
  pkg/watchdog/watchdog_test.go
Labels: bug, c/watchdog

#138 Added git to Docker image
  CHANGELOG.md
  Dockerfile
Labels: enhancement, c/worker

#139 Inject certs in docker step type
  pkg/provisioner/k8sprovisioner.go
  pkg/worker/k8spodtemplating.go
  pkg/worker/k8srunner.go
  pkg/worker/k8srunner_test.go
Labels: enhancement

#148 Skip logging timestamp in worker
  CHANGELOG.md
  pkg/resultstore/logline.go
  pkg/resultstore/loglinewriter.go
  pkg/resultstore/loglinewriter_test.go
  pkg/resultstore/resultstore.go
  pkg/worker/k8srunner.go
Labels: enhancement, c/worker

#151 Removed unused params
  pkg/worker/k8srunner.go
Labels: c/worker, chore

#147 Refactor wharfyml, moved out Docker PodSpec creation
  CHANGELOG.md
  cmd/wharf/utils.go
  internal/errtesting/errtesting.go
  internal/errutil/errutil.go
  internal/errutil/pos.go
  internal/errutil/scoped.go
  internal/errutil/slice.go
  internal/yamltesting/yamltesting.go
  pkg/steps/container.go
  pkg/steps/docker.go
  pkg/steps/helm.go
  pkg/steps/helmpackage.go
  pkg/steps/kubectl.go
  pkg/steps/nugetpackage.go
  pkg/steps/steps.go
  pkg/wharfyml/builtins.go
  pkg/wharfyml/definition.go
  pkg/wharfyml/environment.go
  pkg/wharfyml/environment_test.go
  pkg/wharfyml/error.go
  pkg/wharfyml/error_test.go
  pkg/wharfyml/inputs.go
  pkg/wharfyml/inputs_test.go
  pkg/wharfyml/inputtypes.go
  pkg/wharfyml/nodemapparser.go
  pkg/wharfyml/parse.go
  pkg/wharfyml/parse_test.go
  pkg/wharfyml/position.go
  pkg/wharfyml/stage.go
  pkg/wharfyml/stage_test.go
  pkg/wharfyml/step.go
  pkg/wharfyml/step_test.go
  pkg/wharfyml/steptype.go
  pkg/wharfyml/steptype_container.go
  pkg/wharfyml/steptype_docker.go
  pkg/wharfyml/steptype_helm.go
  pkg/wharfyml/steptype_helmpackage.go
  pkg/wharfyml/steptype_kubectl.go
  pkg/wharfyml/steptype_nugetpackage.go
  pkg/wharfyml/steptype_test.go
  pkg/wharfyml/visit/decode.go
  pkg/wharfyml/visit/mapvisitor.go
  pkg/wharfyml/visit/pos.go
  pkg/wharfyml/visit/tags.go
  pkg/wharfyml/visit/varsub.go
  pkg/wharfyml/visit/verify.go
  pkg/wharfyml/visit/visit.go
  pkg/wharfyml/visitor.go
  pkg/worker/k8spodtemplating.go
  pkg/worker/k8srunner.go
Labels: c/worker, chore

#153 Refactor steps
  CHANGELOG.md
  pkg/steps/container.go
  pkg/steps/docker.go
  pkg/steps/helm.go
  pkg/steps/helmpackage.go
  pkg/steps/k8sscript-helm-package.sh
  pkg/steps/k8sscript-nuget-package.sh
  pkg/steps/kubectl.go
  pkg/steps/nugetpackage.go
  pkg/steps/steps.go
  pkg/wharfyml/parse_test.go
  pkg/wharfyml/visit/mapvisitor.go
  pkg/worker/k8spodtemplating.go
  pkg/worker/k8srunner.go
Labels: c/worker, chore

#156 Added configs for adding configs from provisioner to worker
  CHANGELOG.md
  pkg/config/config.go
  pkg/config/k8senv.go
  pkg/provisioner/k8sprovisioner.go
Labels: enhancement, c/provisioner

#154 Fixed varsub on more complex vars
  CHANGELOG.md
  pkg/varsub/varsub.go
  pkg/varsub/varsub_test.go
Labels: bug

#157 Upgraded wharf-api-client-go to v2.2.1
  CHANGELOG.md
  go.mod
  go.sum
Labels: bug, c/aggregator

#166 Added Codacy badge
  README.md
Labels: documentation

#168 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: chore

#167 Added pkg.go.dev badge
  README.md
Labels: documentation

#162 Replace REG_USER/REG_PASS with HELM_REG_SECRET
  CHANGELOG.md
  pkg/steps/helm.go
  pkg/steps/helmpackage.go
  pkg/steps/k8sscript-helm-package.sh
  pkg/wharfyml/parse_test.go
Labels: enhancement, c/worker

#169 Added protolint
  .protolint.yml
  Makefile
  README.md
  api/workerapi/v1/worker.pb.go
  api/workerapi/v1/worker.proto
  api/workerapi/v1/worker_grpc.pb.go
Labels: documentation, chore

#171 Fixed environment filter bug
  CHANGELOG.md
  pkg/wharfyml/definition.go
  pkg/wharfyml/definition_test.go
Labels: bug, c/worker

#170 Added `wharf run --dry-run` flag
  CHANGELOG.md
  cmd/wharf/run.go
  internal/flagtypes/dryrun.go
  internal/flagtypes/loglevel.go
  pkg/worker/k8srunner.go
Labels: enhancement, c/worker

#174 Removed unused args and returns
  pkg/steps/helm.go
  pkg/steps/helmpackage.go
Labels: chore

#172 Save build results in /tmp via auto build ID
  CHANGELOG.md
  cmd/wharf/run.go
  go.mod
  go.sum
  internal/lastbuild/lastbuild.go
  pkg/provisioner/k8sprovisioner.go
  pkg/resultstore/fs.go
  pkg/resultstore/fs_test.go
  pkg/resultstore/resultstore.go
Labels: enhancement, c/worker

#175 Added BUILD_REF
  cmd/wharf/run.go
  cmd/wharf/utils.go
  cmd/wharf/vars.go
  cmd/wharf/vars_list.go
  cmd/wharf/vars_substitute.go
  internal/lastbuild/lastbuild.go
  internal/pathutil/pathutil.go
  internal/pathutil/pathutil_test.go
  pkg/varsub/source.go
  pkg/wharfyml/builtins.go
  pkg/wharfyml/builtins_test.go
Labels: enhancement, c/worker

#176 Fixed file stores not closing on force quit
  CHANGELOG.md
  cmd/wharf/root.go
  cmd/wharf/run.go
Labels: bug, c/worker

#177 Fixed secret mounting in docker & helm
  pkg/steps/docker.go
  pkg/steps/helm.go
Labels: bug, c/worker

#178 Fixed varsub recursively on fmt.Stringer's
  pkg/varsub/varsub.go
  pkg/varsub/varsub_test.go
Labels: bug, c/worker

#179 Added help command `wharf vars yml`
  CHANGELOG.md
  cmd/wharf/vars_yml.go
  pkg/wharfyml/stage.go
Labels: enhancement

#181 Minor fixes
  cmd/wharf/utils.go
  cmd/wharf/vars_list.go
  internal/gitutil/stats.go
  pkg/steps/container.go
  pkg/steps/docker.go
  pkg/varsub/osenvsource.go
  pkg/varsub/source.go
Labels: enhancement

#180 Added --project-id and PROJECT_ID
  CHANGELOG.md
  cmd/wharf/run.go
  cmd/wharf/utils.go
  cmd/wharf/vars.go
  pkg/provisioner/k8sprovisioner.go
  pkg/steps/container.go
  pkg/steps/docker.go
  pkg/wharfyml/visit/mapvisitor.go
  pkg/wharfyml/visit/visit.go
Labels: enhancement

#163 Fixed build getting stuck on bad config and/or wharf-ci file
  CHANGELOG.md
  go.mod
  go.sum
  pkg/aggregator/aggregator.go
  pkg/aggregator/k8saggregator.go
  pkg/aggregator/k8sevents.go
  pkg/aggregator/k8sportforward.go
  pkg/aggregator/k8sportforward_test.go
  pkg/aggregator/k8sutils.go
  pkg/aggregator/piper.go
  pkg/aggregator/piper_artifactevents.go
  pkg/aggregator/piper_logs.go
  pkg/aggregator/piper_statusevents.go
Labels: bug

#184 Upgraded to wharf-core v2
  CHANGELOG.md
  cmd/wharf/logger.go
  cmd/wharf/root.go
  go.mod
  go.sum
  internal/flagtypes/loglevel.go
  pkg/aggregator/k8saggregator.go
  pkg/config/config.go
  pkg/provisionerapi/provisionerapi.go
  pkg/provisionerapi/worker.go
  pkg/provisionerclient/provisionerclient.go
  pkg/tarstore/tarstore.go
  pkg/watchdog/watchdog.go
  pkg/wharfyml/wharfyml.go
  pkg/worker/k8spodtemplating.go
  pkg/worker/k8srunner.go
  pkg/worker/stagerunner.go
  pkg/worker/worker.go
  pkg/workerapi/workerclient/restclient.go
  pkg/workerapi/workerclient/restclient_test.go
  pkg/workerapi/workerclient/workerclient.go
  pkg/workerapi/workerserver/artifact.go
  pkg/workerapi/workerserver/restserver.go
  pkg/workerapi/workerserver/server.go
  version.go
Labels: chore

#182 Lots of refactor, and 2 bugfixes
  CHANGELOG.md
  Makefile
  README.md
  cmd/wharf/provisioner_serve.go
  cmd/wharf/run.go
  cmd/wharf/utils.go
  internal/testutil/errtesting.go
  internal/testutil/yamltesting.go
  internal/util/pathutil.go
  internal/util/pathutil_test.go
  internal/util/strutil.go
  internal/util/strutil_test.go
  pkg/aggregator/k8sportforward.go
  pkg/aggregator/piper_artifactevents.go
  pkg/aggregator/piper_logs.go
  pkg/aggregator/piper_statusevents.go
  pkg/provisioner/k8sprovisioner.go
  pkg/provisioner/provisionerclient/provisionerclient.go
  pkg/provisioner/provisionerclient/provisionerclient_test.go
  pkg/provisioner/provisionerserver/.gitignore
  pkg/provisioner/provisionerserver/provisionerserver.go
  pkg/provisioner/provisionerserver/worker.go
  pkg/varsub/copier.go
  pkg/varsub/source.go
  pkg/varsub/varsub.go
  pkg/watchdog/watchdog.go
  pkg/wharfyml/builtins.go
  pkg/wharfyml/environment_test.go
  pkg/wharfyml/inputs_test.go
  pkg/wharfyml/parse_test.go
  pkg/wharfyml/stage_test.go
  pkg/wharfyml/step_test.go
  pkg/wharfyml/steptype_test.go
  pkg/worker/k8spodtemplating.go
  pkg/worker/workerclient/grpcclient.go
  pkg/worker/workerclient/grpcclient_test.go
  pkg/worker/workerclient/restclient.go
  pkg/worker/workerclient/restclient_test.go
  pkg/worker/workerclient/workerclient.go
  pkg/worker/workerclient/workerclient_test.go
  pkg/worker/workerserver/.gitignore
  pkg/worker/workerserver/artifact.go
  pkg/worker/workerserver/grpcserver.go
  pkg/worker/workerserver/restserver.go
  pkg/worker/workerserver/server.go
Labels: bug, chore

#183 Release v0.8.0
  CHANGELOG.md
Labels: release

#185 Removed replace directive
  CHANGELOG.md
  go.mod
  go.sum
Labels: chore

#186 Release v0.8.1
  CHANGELOG.md
Labels: release

#189 Fixed build status always set to Failed despite being successful
  CHANGELOG.md
  pkg/aggregator/k8saggregator.go
  pkg/aggregator/piper_statusevents.go
Labels: bug

#190 Release v0.8.2
  CHANGELOG.md
Labels: release
