Repository iver-wharf/wharf-cmd, pull requests merged in 2022-04, with the labels that each got.

#80 Renamed variable `any` -> `anyLine`
  pkg/resultstore/loglinereader.go
Labels: chore

#83 Added aggregator
  CHANGELOG.md
  Makefile
  cmd/aggregator.go
  cmd/aggregator_serve.go
  cmd/run.go
  go.mod
  go.sum
  internal/parallel/parallel.go
  pkg/aggregator/aggregator.go
  pkg/aggregator/k8saggregator.go
  pkg/aggregator/k8saggregator_test.go
  pkg/provisioner/k8sprovisioner.go
  pkg/resultstore/artifact.go
  pkg/resultstore/fs.go
  pkg/resultstore/logline.go
  pkg/resultstore/loglinewriter.go
  pkg/resultstore/resultstore.go
  pkg/resultstore/status.go
  pkg/worker/k8spodtemplating.go
  pkg/worker/k8srunner.go
  pkg/workerapi/workerclient/grpcclient.go
  pkg/workerapi/workerclient/restclient.go
  pkg/workerapi/workerclient/workerclient.go
  pkg/workerapi/workerserver/grpcserver.go
  pkg/workerapi/workerserver/restserver.go
  pkg/workerapi/workerserver/server.go
  test/.wharf-ci.yml
  test/k8s-rbac.yaml
  test/wharf-ci-simple/.wharf-ci.yml
  test/wharf-ci-simple/somefile.txt
Labels: enhancement, c/aggregator

#86 Changed to 0775 permission on resultstore MkdirAll
  pkg/resultstore/fs.go
Labels: bug

#87 Renamed binary from wharf-cmd to wharf
  CHANGELOG.md
  Makefile
  README.md
  cmd/wharf/aggregator.go
  cmd/wharf/aggregator_serve.go
  cmd/wharf/logger.go
  cmd/wharf/main.go
  cmd/wharf/provisioner.go
  cmd/wharf/provisioner_create.go
  cmd/wharf/provisioner_delete.go
  cmd/wharf/provisioner_list.go
  cmd/wharf/provisioner_serve.go
  cmd/wharf/root.go
  cmd/wharf/run.go
  cmd/wharf/watchdog.go
  cmd/wharf/watchdog_serve.go
  docs/build-result-logs.md
  pkg/provisioner/k8sprovisioner.go
  version.go
Labels: chore

#88 Upgraded kubectl & helm images
  pkg/worker/k8spodtemplating.go
Labels: c/worker, chore

#84 Changed to wharf-cmd run path argument instead of flag
  CHANGELOG.md
  cmd/wharf/run.go
  pkg/worker/k8srunner.go
  pkg/worker/worker.go
Labels: enhancement, c/worker

#93 Added varsub listing
  CHANGELOG.md
  cmd/wharf/run.go
  cmd/wharf/vars.go
  internal/gitutil/stats.go
  pkg/varsub/copier_test.go
  pkg/varsub/source.go
  pkg/varsub/varsub.go
  pkg/varsub/varsub_test.go
  pkg/wharfyml/builtins.go
  pkg/wharfyml/builtins_test.go
  pkg/wharfyml/definition.go
  pkg/wharfyml/environment.go
  pkg/wharfyml/environment_test.go
  pkg/wharfyml/parse_test.go
  pkg/wharfyml/steptype_test.go
  pkg/wharfyml/varsub.go
Labels: enhancement

#95 Added completions for --loglevel
  CHANGELOG.md
  cmd/wharf/root.go
  internal/flagtypes/loglevel.go
Labels: enhancement

#90 Added cancelling of builds via system signals
  CHANGELOG.md
  cmd/wharf/aggregator.go
  cmd/wharf/aggregator_serve.go
  cmd/wharf/provisioner.go
  cmd/wharf/provisioner_create.go
  cmd/wharf/provisioner_delete.go
  cmd/wharf/provisioner_list.go
  cmd/wharf/root.go
  cmd/wharf/run.go
  pkg/aggregator/k8saggregator.go
  pkg/resultstore/loglinereader.go
  pkg/resultstore/resultstore.go
  pkg/resultstore/resultstore_test.go
  pkg/resultstore/syncset.go
  pkg/worker/k8srunner.go
Labels: enhancement

#96 Added OS env varsub
  CHANGELOG.md
  cmd/wharf/run.go
  pkg/varsub/osenvsource.go
  pkg/varsub/osenvsource_test.go
Labels: enhancement

#98 `wharf vars`: Hide overridden variables
  CHANGELOG.md
  cmd/wharf/vars.go
  pkg/wharfyml/builtins.go
  pkg/wharfyml/builtins_test.go
Labels: enhancement

#102 Fixed `wharf vars` panicing on hidden values
  CHANGELOG.md
  cmd/wharf/vars.go
Labels: bug

#103 Fixed OS env vars not overriding .wharf-vars.yml
  cmd/wharf/run.go
Labels: bug

#106 Added inputs varsub & validation, and --input flag
  CHANGELOG.md
  cmd/wharf/run.go
  cmd/wharf/vars.go
  internal/flagtypes/keyvalue.go
  pkg/wharfyml/definition.go
  pkg/wharfyml/inputs.go
  pkg/wharfyml/inputtypes.go
  pkg/wharfyml/parse.go
  test/container/.wharf-ci.yml
Labels: enhancement, c/worker

#110 Added `wharf vars sub` command
  CHANGELOG.md
  cmd/wharf/vars.go
  cmd/wharf/vars_list.go
  cmd/wharf/vars_substitute.go
Labels: enhancement

#111 Added completion to `--input key=value` flag
  CHANGELOG.md
  cmd/wharf/run.go
  cmd/wharf/vars.go
  internal/flagtypes/keyvalue.go
Labels: enhancement

#112 Added missing vars to Makefile
  Makefile
Labels: chore

#113 Updated Development docs in README.md
  README.md
Labels: documentation

#114 Added workerserver swaggo docs
  CHANGELOG.md
  Makefile
  pkg/workerapi/workerserver/.gitignore
  pkg/workerapi/workerserver/artifact.go
  pkg/workerapi/workerserver/restserver.go
Labels: documentation

#115 Silenced goimports commandline in Makefile
  Makefile
Labels: chore
